### ISSUE TITLE
Bug with LPQPBridge?

### ISSUE THREAD

**Issue by 1ozturkbe** [chriscoey/DaChoppa.jl#1] opened 2018-10-05 16:56 UTC
(I am running convexBurn.jl in commit  7ec6e43 of soromotoropt/master). 
I tried solving a relaxation of the piecewise linearization (a QP) and I got the following error:
``` julia
C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\soromotoropt>julia convexBurn.jl
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] optimize!(::DaChoppa.DaChoppaNonlinearModel) at C:\Users\Berk\.julia\v0.6\DaChoppa\src\algorithm.jl:154
 [2] optimize!(::MathProgBase.SolverInterface.NonlinearToLPQPBridge) at C:\Users\Berk\.julia\v0.6\MathProgBase\src\SolverInterface\nonlinear_to_lpqp.jl:74
 [3] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\Berk\.julia\v0.6\JuMP\src\solvers.jl:175
 [4] srm_model(::DaChoppa.DaChoppaSolver, ::Int64, ::Array{Float64,1}, ::Int64) at C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\soromotoropt\convexBurn.jl:87
 [5] include_from_node1(::String) at .\loading.jl:576
 [6] include(::String) at .\sysimg.jl:14
 [7] process_options(::Base.JLOptions) at .\client.jl:305
 [8] _start() at .\client.jl:371
while loading C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\soromotoropt\convexBurn.jl, in expression starting on line 103
```
Not sure why the original set of constraints was working but not this one. Lmk if you have ideas @chriscoey. The error messages aren't too helpful :/

**Comment by chriscoey** [comment] 2018-10-05 17:14
Can you try checking out the following branch and running Pkg.build("Gurobi") and then restarting Julia and running your script again? https://github.com/JuliaOpt/Gurobi.jl/pull/161

**Comment by 1ozturkbe** [comment] 2018-10-05 22:34
Hey Chris, unfortunately I will be afk until Sunday afternoon. I can try then and let you know.

**Comment by chriscoey** [comment] 2018-10-06 04:11
the issue is either in the bridge package or due to the fact that one of your constraints was not written convexly. closing the issue and will show you the fix offline.

**Closed as completed by chriscoey** 2018-10-06 04:11 UTC
